---
- hosts: all
  remote_user: root
  gather_facts: false
  tasks:
    - name: Running tasks/main_K8s_resources.yaml instead of 'main'
      import_role:
        name: ../
        tasks_from: main_K8s_resources.yaml
