---
- hosts: master
  remote_user: root
  gather_facts: false
  vars:
    th_version: "{{ th_version }}"
    interval: "{{ interval }}"
    influxdb_ip: "{{ influxdb_ip }}"
    database_name: "{{ database_name }}"
    db_username: "{{ db_username | default('') }}"
    db_username_pass: "{{ db_username_pass | default('') }}"

  tasks:
  - name: Running tasks/main_master.yaml instead of 'main'
    import_role:
      name: ../telegraf_ansible_arcsight_th_cluster
      tasks_from: main_master
    
  vars_prompt:
  - name: th_version
    prompt: "TH version, choose 3.4 or 3.5"
    private: no

  - name: interval
    prompt: "Scrape metrics seconds interval"
    private: no  
      
  - name: influxdb_ip
    prompt: "Influxdb ip"
    private: no
    
  - name: database_name
    prompt: "Influxdb database name where the metrics will be stored"
    private: no

  - name: db_username
    prompt: "Influxdb database username, leave empty if no user is needed"
    private: no 

  - name: db_username_pass
    prompt: "Influxdb database username's password, leave empty if no user is needed"
    private: yes
    
- hosts: workers
  remote_user: root
  gather_facts: false
  vars:
    th_version: "{{ th_version }}"
    interval: "{{ interval }}"
    influxdb_ip: "{{ influxdb_ip }}"
    database_name: "{{ database_name }}"
    db_username: "{{ db_username | default('') }}"
    db_username_pass: "{{ db_username_pass | default('') }}"

  tasks:
  - name: Running tasks/main_workers.yaml instead of 'main'
    import_role:
      name: ../telegraf_ansible_arcsight_th_cluster
      tasks_from: main_workers
  
  # vars:
  #   interval: "{{ interval }}"
  #   influxdb_ip: "{{ influxdb_ip }}"
  #   db: "{{ database_name }}"

  # vars_prompt:
  # - name: interval
  #   prompt: "Scrape metrics interval"
  #   private: no  
      
  # - name: influxdb_ip
  #   prompt: "Please provide the Influxdb ip"
  #   private: no
    
  # - name: database_name
  #   prompt: "Please provide the Influxdb database name where the metrics will be stored"
  #   private: no    