---
- hosts: all
  remote_user: root
  gather_facts: false
  vars:
    th_version: "3.5"
    proxyk: "http://web-proxy.am.softwaregrp.net:8080"
    interval: "10"
    influxdb_ip: "15.214.128.179"
    database_name: "system_test"
    db_username: ""
    db_username_pass: ""

  tasks:
  - name: Running tasks/main_all.yaml instead of 'main'
    import_role:
      name: ../telegraf_ansible_arcsight_th_cluster
      tasks_from: main_all.yaml