---
- hosts: master
  remote_user: root
  gather_facts: false
  tasks:
  - name: Configuring master.
    include_role:
      name: ../
      tasks_from: main_master
  
  vars:
    interval: "{{ interval }}"
    influxdb_ip: "{{ influxdb_ip }}"
    db: "{{ database_name }}"
    db_username: "{{ db_username | default('') }}"
    db_username_pass: "{{ db_username_pass | default('') }}"    
    
- hosts: workers
  remote_user: root
  gather_facts: false
  tasks:
  - name: Configuring workers
    include_role:
      name: ../
      tasks_from: main_workers
  
  vars:
    interval: "{{ interval }}"
    influxdb_ip: "{{ influxdb_ip }}"
    db: "{{ database_name }}"
    db_username: "{{ db_username | default('') }}"
    db_username_pass: "{{ db_username_pass | default('') }}"    