---
- hosts: master
  remote_user: root
  gather_facts: false
  tasks:
  - name: Running tasks/main_master.yaml instead of 'main'
    import_role:
      name: ../
      tasks_from: main_master
    
- hosts: workers
  remote_user: root
  gather_facts: false
  tasks:
  - name: Running tasks/main_workers.yaml instead of 'main'
    import_role:
      name: ../
      tasks_from: main_workers